# 不要滥用断言

> 原文：<https://dev.to/yloganathan/do-not-abuse-the-assert-1cfm>

断言是为了让程序员发现错误或不应该发生的情况。如果所有断言都被删除，程序应该正常执行。实用程序员状态中的断言编程部分

> 每当你发现自己在想“但是这当然不可能发生”，就添加代码来检查它。

很容易采用 advise 和 add 断言来处理每个负面情况。大多数语言都提供了一种在调试代码中进行这种检查的便捷方式，在测试后的生产部署中通常会关闭这种检查。断言不应用于正常检查(即错误处理)

## 不使用断言进行正常的错误处理

空检查(Null checks)—考虑一个 python 例子，其中我们将访问一个 dict。

```
def create_auth_header(oauth):
    assert oauth
    return {"Authorization": "Bearer " + oauth['access_token']} 
```

这里的 Assert 没有提供语言错误所没有提供的任何额外内容。TypeError 或 KeyError(在 python 中)提供了比 AssertionError 更多的信息。与 try and catch 非常相似，遍布代码的断言会分散从业务逻辑中读取代码的程序员的注意力。

验证用户输入 —一个好的程序总是验证用户输入，但是这不应该用断言来完成。出于这个原因，例外是存在的。在 Python 中，在优化模式下运行程序时，可以忽略所有断言。所有用户输入验证都可能被另一个开发人员意外绕过。

## 那我什么时候用断言呢？

当您认为原因和结果被大量代码分开时，使用断言作为一种工具来提醒您。有没有遇到过这样的情况，一段代码中的错误在完全不同的模块中表现为奇怪的行为，使调试成为一场噩梦？我们都经历过。当我们写代码时，我们试图通过问很多“如果…会怎样”的问题来避免这种情况。如果输入为空怎么办？如果找不到我要找的钥匙怎么办？如果世界末日了呢？如果原因(即输入为空)和结果(即系统以 TypeError 退出)之间的距离不在函数、方法或类本身内，则需要断言。

让我们看一个例子，在这个例子中，assert 可以为我们节省很多时间。这个例子摘自 Python wiki。请检查那里的其他例子。它们对理解断言很有帮助。

```
class PrintQueueList:
   ...
     def add(self, new_queue):
       assert new_queue not in self._list, \
          "%r is already in %r" % (self, new_queue)
       assert isinstance(new_queue, PrintQueue), \
          "%r is not a print queue" % new_queue 
```

这里，assert 用于检查列表中的重复项。在这种情况下，知道列表中不能有任何重复项(尤其是重复项的影响可能只有在执行过程中才会明显，并且症状可能不会直接指向根本原因),那么快速失败并在晚上睡个好觉是有好处的。

总而言之，

1.  如果语言很快就会失败，就不要使用断言来检查输入
2.  不要对用户输入验证使用断言
3.  不要关闭生产中的断言
4.  当原因和结果之间的距离不是直接的时候，请谨慎使用断言，从而减少副作用
5.  一定要使用断言来防止你的系统由于程序员的错误而进入不一致或者无性能的状态。断言对于运行时非常有用(例如外部原因错误)。“我们没有测试这个案例，因为我们从来没有想到我们可以做到这一点”，即“永远不会发生”的事情